Lesson6CF/Lesson6CF/Models/NdtBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lesson6CF.Models
{
    public class NdtBook
    {
        [Key]
        public int NdtId { get; set; }
        public string NdtBookId { get; set; }
        public string NdtTitle { get; set; }
        public string NdtAuthor { get; set; }
        public int NdtYear { get; set; }
        public string NdtPulisher { get; set; }
        public string NdtPicture { get; set; }
        public int NDTCategoryId { get; set; }
        //thuộc tính quan hệ 
        public virtual NdtCategory NdtCategory { get; set; }

    }
}

Lesson6CF/Lesson6CF/Models/NdtBookStore.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Lesson6CF.Models
{
    public class NdtBookStore:DbContext

    {
        public NdtBookStore() : base("NdtBookStoreConnectionString") { }
        // khai báo các thuộc tính 
        public DbSet<NdtCategory> NdtCategories { get; set; }
        public DbSet<NdtBook> NdtBooks { get; set; }
    }
}

Lesson6CF/Lesson6CF/Models/NdtCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lesson6CF.Models
{
    public class NdtCategory
    {
        [Key]
        public int NdtId { get; set; }
        public string NdtCategoryName { get; set; }
        //thuộc tính quan hệ 
        public virtual ICollection<NdtBook> NdtBooks { get; set; }

    }
}

Lesson6CF/Lesson6CF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson6CF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lesson6CF/Lesson6CF/Controllers/NdtBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lesson6CF.Models;

namespace Lesson6CF.Controllers
{
    public class NdtBooksController : Controller
    {
        private NdtBookStore db = new NdtBookStore();

        // GET: NdtBooks
        public ActionResult Index()
        {
            return View(db.NdtBooks.ToList());
        }

        // GET: NdtBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NdtBook ndtBook = db.NdtBooks.Find(id);
            if (ndtBook == null)
            {
                return HttpNotFound();
            }
            return View(ndtBook);
        }

        // GET: NdtBooks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NdtBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NdtId,NdtBookId,NdtTitle,NdtAuthor,NdtYear,NdtPulisher,NdtPicture,NDTCategoryId")] NdtBook ndtBook)
        {
            if (ModelState.IsValid)
            {
                db.NdtBooks.Add(ndtBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ndtBook);
        }

        // GET: NdtBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NdtBook ndtBook = db.NdtBooks.Find(id);
            if (ndtBook == null)
            {
                return HttpNotFound();
            }
            return View(ndtBook);
        }

        // POST: NdtBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NdtId,NdtBookId,NdtTitle,NdtAuthor,NdtYear,NdtPulisher,NdtPicture,NDTCategoryId")] NdtBook ndtBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ndtBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ndtBook);
        }

        // GET: NdtBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NdtBook ndtBook = db.NdtBooks.Find(id);
            if (ndtBook == null)
            {
                return HttpNotFound();
            }
            return View(ndtBook);
        }

        // POST: NdtBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NdtBook ndtBook = db.NdtBooks.Find(id);
            db.NdtBooks.Remove(ndtBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lesson6CF/Lesson6CF/Controllers/NdtCategoryController.cs
using Lesson6CF.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson6CF.Controllers
{
    public class NdtCategoryController : Controller
    {
        private static NdtBookStore ndtDb;
        public NdtCategoryController()
        {
            ndtDb = new NdtBookStore();

        }
        // GET: NdtCategory
        public ActionResult NdtIndex()
        {
            /*
             * khởi tạo DbContext
             * EF sẽ tìm thông tin kết nối 
             * */
           // NdtBookStore ndtDb = new NdtBookStore();
            var ndtCategoris = ndtDb.NdtCategories.ToList();
            return View(ndtCategoris);
        }
        public ActionResult NdtCreate()
        {
            var ndtCategory = new NdtCategory();
            return View(ndtCategory);
        }
        [HttpPost]
        public ActionResult NdtCreate(NdtCategory ndtCategory)
        {
            ndtDb.NdtCategories.Add(ndtCategory);
            ndtDb.SaveChanges();
            return RedirectToAction("NdtIndex");
        }
    }
}

Lesson6CF/Lesson6CF/Views/NdtCategory/NdtIndex.cshtml
@model IEnumerable<Lesson6CF.Models.NdtCategory>

@{
    ViewBag.Title = "NdtIndex";
}

<h2>NdtIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NdtCategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NdtCategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NdtId }) |
            @Html.ActionLink("Details", "Details", new { id=item.NdtId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NdtId })
        </td>
    </tr>
}

</table>

Lesson6CF/Lesson6CF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nguyễn Danh Trường</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nguyễn Danh Trường ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Ndt : NdtCategory", "NdtIndex", "NdtCategory", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Ndt : Book", "Index", "NdtBooks", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>